# Generated by Django 6.0.6 on 2026-09-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('INSTRUCTOR', 'Наставник'), ('STUDENT', 'Студент'), ('BOOKREADER', 'Книгочей')], default='BOOKREADER', max_length=20),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='code',
            field=models.CharField(choices=[('STUDENT', 'Студент'), ('INSTRUCTOR', 'Педагог'), ('ADMIN', 'Админ'), ('BOOKREADER', 'Книгочей')], max_length=20, primary_key=True, serialize=False),
        ),
    ]
