# Generated by Django 6.0.6 on 2026-08-29 18:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('published', 'Опубликован'), ('draft', 'Черновик'), ('archieved', 'Архивный')], default='draft', max_length=20)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Узел карты',
                'verbose_name_plural': 'Узлы карты',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Дорожная карта',
                'verbose_name_plural': 'Дорожные карты',
            },
        ),
        migrations.CreateModel(
            name='NodeRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('question_order', models.JSONField(default=list, help_text='Список UUID вопросов в порядке на момент ревизии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='roadmap.node', verbose_name='Ревизия')),
            ],
            options={
                'verbose_name': 'Ревизия узла',
                'verbose_name_plural': 'Ревизии узлов',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='node',
            name='current_revision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_revision', to='roadmap.noderevision', verbose_name='Текущая ревизия'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='roadmap.node', verbose_name='Вопрос к узлу')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='QuestionRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='roadmap.question')),
            ],
            options={
                'verbose_name': 'Ревизия вопроса',
                'verbose_name_plural': 'Ревизии вопросов',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='current_revision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_revision_for_question', to='roadmap.questionrevision'),
        ),
        migrations.AddField(
            model_name='node',
            name='roadmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='roadmap.roadmap', verbose_name='Дорожная карта'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('node', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('roadmap', 'order')},
        ),
    ]
