# Generated by Django 6.0.6 on 2026-09-11 14:20

import core.utils.uploaders
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.uploaders.node_background_upload_to),
        ),
    ]
