# Generated by Django 6.0.6 on 2026-09-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_node_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='wave',
            field=models.FloatField(default=0.5, help_text='Позиция по вертикали: 0.0 — низ, 1.0 — верх', verbose_name='Высота на карте'),
        ),
    ]
