# Generated by Django 6.0.6 on 2026-09-13 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0003_node_wave'),
    ]

    operations = [
        migrations.AddField(
            model_name='noderevision',
            name='book',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='noderevision',
            name='chapter',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='noderevision',
            name='narrator_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='noderevision',
            name='narrator_role',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='noderevision',
            name='tag',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='noderevision',
            name='task',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='noderevision',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='noderevision',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='roadmap.node', verbose_name='Узел'),
        ),
        migrations.AlterField(
            model_name='noderevision',
            name='question_order',
            field=models.JSONField(blank=True, default=list, help_text='Список UUID вопросов в порядке на момент ревизии'),
        ),
    ]
