# Generated by Django 6.0.6 on 2026-09-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0004_noderevision_book_noderevision_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='lore',
            field=models.TextField(blank=True, help_text='Лор для узла. Каждая новая страница-отдельный абзац', verbose_name='Лор узла'),
        ),
    ]
