# Generated by Django 6.0.6 on 2026-09-19 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0005_node_lore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNodeProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_passed', models.BooleanField(default=False, verbose_name='Пройден')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='Количество правильных ответов')),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0, help_text='XP, начисленные при первом прохождении')),
                ('passed_at', models.DateTimeField(blank=True, help_text='Когда узел впервые пройден', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='roadmap.node', verbose_name='Узел карты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс по узлу',
                'verbose_name_plural': 'Прогресс по узлам',
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['user', 'is_passed'], name='roadmap_use_user_id_ffcb7b_idx')],
                'unique_together': {('user', 'node')},
            },
        ),
    ]
