# Generated by Django 6.0.6 on 2026-09-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0006_usernodeprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernodeprogress',
            old_name='passed_at',
            new_name='first_passed_at',
        ),
    ]
