# Generated by Django 6.0.6 on 2026-10-01 15:06

import core.apps.roadmap.uploaders
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0007_rename_passed_at_usernodeprogress_first_passed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapShard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.apps.roadmap.uploaders.shard_image_upload_to, verbose_name='Изображение')),
                ('node', models.OneToOneField(help_text='Узел, за который выдаётся осколок', on_delete=django.db.models.deletion.CASCADE, related_name='shard', to='roadmap.node', verbose_name='Узел')),
            ],
        ),
        migrations.CreateModel(
            name='UserMapShard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recieved_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда получен')),
                ('shard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shards', to='roadmap.mapshard', verbose_name='Осколок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_shards', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Осколок пользователя',
                'verbose_name_plural': 'Осколки пользователей',
                'ordering': ('-recieved_at',),
                'indexes': [models.Index(fields=['user', '-recieved_at'], name='roadmap_use_user_id_dbec2e_idx')],
                'unique_together': {('user', 'shard')},
            },
        ),
    ]
