# Generated by Django 6.0.6 on 2026-10-01 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0008_mapshard_usermapshard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermapshard',
            options={'ordering': ('-received_at',), 'verbose_name': 'Осколок пользователя', 'verbose_name_plural': 'Осколки пользователей'},
        ),
        migrations.RemoveIndex(
            model_name='usermapshard',
            name='roadmap_use_user_id_dbec2e_idx',
        ),
        migrations.RenameField(
            model_name='usermapshard',
            old_name='recieved_at',
            new_name='received_at',
        ),
        migrations.AddIndex(
            model_name='usermapshard',
            index=models.Index(fields=['user', '-received_at'], name='roadmap_use_user_id_05a706_idx'),
        ),
    ]
